image: 'nbulai/ruby-chromedriver:latest'
  
stages:
  - test
  
run_scripts:
  stage: test
  script:
    - bundle update --bundler
    - bundle install
    - bundle exec cucumber
  artifacts:
    paths:
      - results/